# Generated by Django 5.2 on 2025-04-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_remove_user_user_user_usernam_6d9439_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
